### ISSUE TITLE
How to configure proxy

### ISSUE THREAD

**Issue by frnandu** [pascal-zarrad/tc-discord-webhooks#18]
I'm trying to use it on a server that needs proxy.
I've tried setting TEAMCITY_SERVER_OPTS with -Dhttp.proxyHost=.... -Dhttp.proxyPort=... -Dhttps.proxyHost=.... -Dhttps.proxyPort=.... -Dhttp.nonProxyHosts=.... 
and restarting teamcity, then even uninstall and install the plugin again.

Also tried to add

teamcity.http.nonProxyHosts=...
teamcity.https.proxyHost=...
teamcity.https.nonProxyHosts=...
teamcity.http.proxyHost=...
teamcity.https.proxyPort=...
teamcity.http.proxyPort=...

on internal.properties

but everytime I get this:

`[2021-02-13 23:42:24,271]  ERROR [9@58f69f86'; Normal executor 1] - notificator.DiscordNotificator - Failed to send the WebHook!
org.apache.http.conn.HttpHostConnectException: Connect to discord.com:443 [discord.com/162.159.136.232, discord.com/162.159.135.232, discord.com/162.159.128.233, discord.com/162.159.137.232, discord.com/162.159.138.232] failed: Connection timed out (Connection timed out)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.github.playerforcehd.tcdiscordwebhooks.discord.DiscordWebHookProcessor.sendDiscordWebHook(DiscordWebHookProcessor.java:95)
	at com.github.playerforcehd.tcdiscordwebhooks.discord.DiscordWebHookProcessor.sendDiscordWebHook(DiscordWebHookProcessor.java:73)
	at com.github.playerforcehd.tcdiscordwebhooks.notificator.DiscordNotificator.processNotify(DiscordNotificator.java:145)
	at com.github.playerforcehd.tcdiscordwebhooks.notificator.DiscordNotificator.notifyBuildFailed(DiscordNotificator.java:258)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener$NotificatorEventAdapter.notifyBuildFailureWatchers(UserRulesAwareNotificationListener.java:237)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener$NotificatorEventAdapter.buildFailedSubsequent(UserRulesAwareNotificationListener.java:192)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener$NotificatorEventAdapter.access$400(UserRulesAwareNotificationListener.java:148)
	at jetbrains.buildServer.notification.impl.UserRulesAwareNotificationListener.buildFailed(UserRulesAwareNotificationListener.java:23)
	at jetbrains.buildServer.notification.NotificationProcessor$5.call(NotificationProcessor.java:3)
	at jetbrains.buildServer.notification.NotificationProcessor$19.run(NotificationProcessor.java:8)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 22 more
`

**Comment by pascal-zarrad** [comment]
Hello @frnandu,

TC Discord Webhooks has never been tested using a proxy and therefore it is no surprise that it doesn't work.
I will setup a system with a proxy in front of it and check the issue. If it does not work (what I definitly believe), I might provide an update with proxy support.
Please note that due to other projects and the additional effort necessary due to the fact that I will need to setup a server with proxy configuration, it can take some time until the update is released.

**Comment by pascal-zarrad** [comment]
Proxy support has been merged. A release containing the change will be created soon.
